from __future__ import annotations

from ._types import CellLibraryEntry, CellLibraryMetadata, CellLibrarySummary


class Pdk:
	def __init__(self, core) -> None: ...
	@classmethod
	def minimal(cls, name: str = "py-minimal-pdk") -> Pdk: ...
	@classmethod
	def from_json(cls, payload: str) -> Pdk: ...
	@property
	def name(self) -> str: ...
	def to_json(self) -> str: ...
	@property
	def active_timing_corner(self) -> str | None: ...
	def timing_corner_names(self) -> list[str]: ...
	def with_active_timing_corner(self, name: str) -> Pdk: ...
	@property
	def cell_library_name(self) -> str: ...
	@property
	def cell_library_version(self) -> str | None: ...
	@property
	def cell_library_source(self) -> str | None: ...
	def cell_library_metadata(self) -> CellLibraryMetadata: ...
	def cell_library_kinds(self) -> list[str]: ...
	def cell_library_entries(self) -> list[CellLibraryEntry]: ...
	def cell_library_summary(self) -> CellLibrarySummary: ...
	def cell_library_entries_by_kind(self, kind: str) -> list[CellLibraryEntry]: ...
	def cell_library_entry(self, cell_name: str) -> CellLibraryEntry | None: ...
	def merge_characterized_library_json(self, serialized_entry: str) -> Pdk: ...
	def merge_characterized_library_entries(self, serialized_entries: list[str]) -> Pdk: ...

__all__: list[str]